//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSAF16072021.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopicTrainee
    {
        public int id_topictrainer { get; set; }
        public int id_topic { get; set; }
        public Nullable<System.DateTime> startday { get; set; }
        public int id_trainee { get; set; }
        public Nullable<byte> dadelete { get; set; }
    
        public virtual Topic Topic { get; set; }
        public virtual Trainee Trainee { get; set; }
    }
}
