//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSAF16072021.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trainer()
        {
            this.TopicTrainers = new HashSet<TopicTrainer>();
        }
    
        public int trainer_id { get; set; }
        public string trainer_name { get; set; }
        public string trainer_password { get; set; }
        public string trainer_email { get; set; }
        public string trainer_telephone { get; set; }
        public string trainer_address { get; set; }
        public Nullable<byte> dadelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TopicTrainer> TopicTrainers { get; set; }
    }
}
