//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSAF16072021.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trainee()
        {
            this.TopicTrainees = new HashSet<TopicTrainee>();
        }
    
        public int trainee_id { get; set; }
        public string trainee_name { get; set; }
        public string trainee_password { get; set; }
        public string trainee_email { get; set; }
        public string trainee_telephone { get; set; }
        public string trainer_address { get; set; }
        public Nullable<byte> dadelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TopicTrainee> TopicTrainees { get; set; }
    }
}
