//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSAF16072021.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training
    {
        public int training_id { get; set; }
        public string training_name { get; set; }
        public string training_password { get; set; }
        public string training_email { get; set; }
        public string training_telephone { get; set; }
        public string training_address { get; set; }
        public Nullable<byte> dadelete { get; set; }
    }
}
